branches:
  only:
  - master
language: python
python:
- 3.7
install:
- pip install -r requirements.txt
script:
- pelican content -o output -s publishconf.py
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: "jflnL+Y+JyNLwENvzWHbhthUVOLCVsVGXWMJnuBkXyVSJJ/guUJpsEbGj3/rALchGyAo3yodGFMWM6da1wwzxsJ7yshr1UgZsidPWradQePcl6NL/YdApGyeElEyOmRPa3mHSoUwamJk/PqiNCNAmWZ3De9OTsiz+JTBi53c1VPwimSN7KusDPhcBafPv424Tdf6Pj/QBXCo6UrsAbrF+bV4CWuRFlohx2gYW0uHS16ecdZe7TYXt6ZKsWmkMmshVZjtJ12Lh8H5UmXxk/c0fZU1CvfNv5vzb00bHcmz6xfrDMyJ6tAC0gRTXshwD9iqkFG2WszClfaRGJ1C3jnNuaHgisGquz7uK6OXT9ALYAYKU9wmXd12PrHZxBRmOOPwoB2br1SHBzKC6H7l+sv+jXqkCA18pzOUyer/rMl19DJBjSjM2lZwnpUmGxSFSJnlcednr8PEzV6/Uea9+5ext/FYSS6I/EYIE36hPy3vbvG5q7l4OrR7gEYGb2ztwYetYtwLh6VNbgi9m61L54hNpaf0DBtax41UwgR05mpdqzCxd06LOMMEWK+x9bO+SxtRopexq/AE+pt7MLCrzCo4zCleujYCpVTQIQj87c22rgoc6KzaFEk5M4NDTMgKIHOU5EV/Wcl89sUvVIeY8bxghfrwBGJvxDsyG36S7VHOBQI="
after_success: bash deploy.sh
